keywords = [
    'javascript', 'python', 'c#', 'java', 'c++', 'c', 'ruby', 'swift', 'kotlin',
    'go', 'rust', 'typescript', 'php', 'r', 'scala', 'perl', 'dart', 'haskell',
    'elixir', 'erlang', 'lua', 'objective-c', 'bash', 'sql', 'f#', 'clojure', 
    'groovy', 'julia', 'visual basic', 'vba',
    'powershell', 'html', 'css', 'bootstrap', 'tailwind', 'sass', 'scss' 'react',
    'angular', 'vue.js', 'svelte', 'ember.js', 'jquery', 'vite', 'redux', 
    'next.js', 'nuxt.js', 'gatsby', 'three.js', 'node.js', 'express.js',
    'django', 'flask', 'ruby on rails', 'spring boot', 'laravel', 'asp.net',
    'fastapi', 'nestjs', 'koa.js', 'tsoa', 'fastify', 'phoenix', 'gin',
    'play framework (scala)', 'graphql', 'rest apis', 'grpc', 'apache kafka',
    'rabbitmq', 'celery', 'socket.io', 'firebase', 'supabase', 'hasura', 'mysql',
    'postgresql', 'mongodb', 'sqlite', 'mariadb', 'oracle database', 'microsoft sql server',
    'redis', 'cassandra', 'couchbase', 'elasticsearch', 'neo4j', 'dynamodb',
    'firebase realtime database', 'influxdb', 'snowflake', 'cockroachdb', 'arangodb',
    'amazon rds', 'google cloud firestore', 'docker', 'kubernetes', 'terraform',
    'ansible', 'jenkins', 'gitlab ci/cd', 'github actions', 'circleci', 'travis ci',
    'aws (amazon web services)', 'ec2', 's3', 'lambda', 'rds', 'cloudfront', 'iam',
    'microsoft azure', 'azure functions', 'azure devops', 'azure kubernetes service (aks)',
    'google cloud platform (gcp)', 'google app engine', 'google kubernetes engine (gke)',
    'bigquery', 'heroku', 'digitalocean', 'vercel', 'netlify', 'nginx', 'apache http server',
    'prometheus', 'grafana', 'istio', 'helm', 'vagrant', 'puppet', 'chef', 'react native',
    'flutter', 'xamarin', 'swiftui', 'android sdk', 'kotlin multiplatform', 'ionic',
    'cordova', 'phonegap', 'unity (for mobile games)', 'arkit (apple augmented reality)',
    'arcore (google augmented reality)', 'tensorflow', 'pytorch', 'keras',
    'scikit-learn', 'pandas', 'numpy', 'matplotlib', 'seaborn', 'jupyter notebook',
    'opencv', 'apache spark', 'hadoop', 'hive', 'tableau', 'power bi', 'apache flink',
    'dask', 'xgboost', 'lightgbm', 'catboost', 'spacy', 'nltk', 'hugging face transformers',
    'weka', 'rapidminer', 'knime', 'unity', 'unreal engine', 'godot', 'cryengine',
    'phaser.js', 'pygame', 'blender (3d modeling)', 'maya (3d modeling)',
    'zbrush (3d sculpting)', 'substance painter (texturing)', 'aseprite (pixel art)',
    'ethereum', 'solidity', 'web3.js', 'ethers.js', 'hyperledger', 'binance smart chain',
    'polkadot', 'cardano', 'ipfs (interplanetary file system)', 'truffle', 'hardhat',
    'metamask', 'openzeppelin', 'chainlink', 'algorand', 'tezos', 'avalanche',
    'kali linux', 'metasploit', 'wireshark', 'nmap', 'burp suite', 'owasp',
    'hashcat', 'john the ripper', 'snort', 'splunk', 'nessus', 'openvas',
    'aircrack-ng', 'pfsense', 'tor', 'vpn (virtual private network)', 'zero trust architecture',
    'linux (ubuntu, fedora, centos, debian, arch, etc.)', 'windows', 'macos',
    'android', 'ios', 'freebsd', 'chrome os', 'unix', 'git', 'github', 'gitlab',
    'bitbucket', 'svn (subversion)', 'mercurial', 'jira', 'trello', 'asana', 'slack',
    'microsoft teams', 'confluence', 'selenium', 'cypress', 'jest', 'mocha',
    'chai', 'jasmine', 'puppeteer', 'postman', 'soapui', 'jmeter', 'katalon studio',
    'appium', 'testng', 'cucumber', 'loadrunner', 'visual studio code', 'intellij idea',
    'pycharm', 'eclipse', 'atom', 'sublime text', 'notepad++', 'docker compose',
    'kubernetes helm', 'anaconda', 'jira', 'figma', 'adobe photoshop', 'adobe illustrator',
    'blender', 'unity', 'unreal engine', 'raspberry pi', 'arduino',
    'tensor processing unit (tpu)', 'nvidia cuda', 'opencl', 'webassembly (wasm)',
    'graphql', 'rest api', 'oauth', 'jwt (json web tokens)'
    ]
