# keep artifacts like '.js' or juts the prefixes? (vue, ember, next, nuxt, etc.)
# create logic after filtering to combine keywords like 'google cloud platform' + 'gcp'?
keywords = [
    'javascript', 'python', 'c#', 'java', 'c++', 'c', 'ruby', 'swift', 'kotlin',
    'go', 'rust', 'typescript', 'php', 'r', 'scala', 'perl', 'dart', 'haskell',
    'elixir', 'erlang', 'lua', 'objective-c', 'bash', 'sql', 'f#', 'clojure', 
    'groovy', 'julia', 'visual basic', 'vba',
    'powershell', 'html', 'css', 'bootstrap', 'tailwind', 'sass', 'scss' 'react',
    'angular', 'vue.js', 'svelte', 'ember.js', 'jquery', 'vite', 'redux', 
    'next.js', 'nuxt.js', 'gatsby', 'three.js', 'node.js', 'express.js',
    'django', 'flask', 'ruby on rails', 'spring boot', 'laravel', 'asp.net',
    'fastapi', 'nestjs', 'koa.js', 'tsoa', 'fastify', 'xml', 'phoenix', 'gin',
    'graphql', 'rest', 'grpc', 'kafka', 'pulsar',
    'rabbitmq', 'celery', 'socket.io', 'firebase', 'supabase', 'hasura', 'mysql',
    'postgresql', 'mongodb', 'sqlite', 'nosql' 'mariadb', 'oracle', 'sql server',
    'redis', 'cassandra', 'couchbase', 'elasticsearch', 'neo4j', 'dynamodb',
    'firebase realtime database', 'influxdb', 'snowflake', 'cockroachdb', 'arangodb',
    'firestore', 'docker', 'kubernetes', 'terraform',
    'ansible', 'jenkins', 'gitlab', 'github actions', 'circleci', 'travis ci',
    'aws', 'ec2', 's3', 'lambda', 'rds', 'cloudfront', 'iam',
    'azure', 'azure functions', 'azure devops', 'aks',
    'google cloud platform', 'gcp', 'google app engine', 'gke',
    'bigquery', 'vercel', 'nginx', 'apache',
    'prometheus', 'grafana', 'istio', 'puppet', 'chef', 'react native',
    'flutter', 'xamarin', 'swiftui', 'android', 'ionic',
    'arkit', 'arcore', 'tensorflow', 'pytorch', 'keras',
    'scikit-learn', 'pandas', 'numpy', 'matplotlib', 'seaborn', 'jupyter',
    'opencv', 'hadoop', 'hive', 'tableau', 'power bi',
    'dask', 'xgboost', 'lightgbm', 'catboost', 'spacy', 'nltk',
    'weka', 'rapidminer', 'knime', 'unity', 'unreal engine', 'godot', 'cryengine',
    'phaser', 'pygame', 'blender', 'maya',
    'zbrush', 'substance painter', 'aseprite',
    'ethereum', 'solidity', 'web3.js', 'ethers.js', 'hyperledger',
    'polkadot', 'truffle', 'hardhat', 'chainlink', 'algorand', 'tezos',
    'metasploit', 'wireshark', 'burp suite',
    'john the ripper', 'snort', 'splunk', 'nessus', 'openvas',
    'aircrack-ng',
    'linux', 'windows', 'macos', 'ios', 'freebsd', 'chrome os', 'git', 'github', 'gitlab',
    'bitbucket', 'svn', 'mercurial', 'jira', 'trello',
    'selenium', 'cypress', 'jest', 'mocha',
    'chai', 'jasmine', 'puppeteer', 'postman', 'soap', 'jmeter', 'katalon studio',
    'appium', 'testng', 'cucumber', 'loadrunner',
    'docker compose', 'anaconda', 'jira', 'figma',
    'blender', 'unreal engine', 'arduino',
    'opencl', 'webassembly',
    'graphql', 'rest', 'oauth', 'jwt'
    ]
